# Generated by Django 4.1.5 on 2023-01-19 10:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='provider',
            field=models.ManyToManyField(related_name='bank', through='api.BankAccount', to='api.provider'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='nit_provider',
            field=models.CharField(max_length=11, validators=[api.models.validate_nit]),
        ),
    ]
